import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";

import "./globals.css";

import { VisualDimensions } from "./visual-dimensions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <VisualDimensions />
      <html lang="en">
        <body
          className={cn(inter.className, "h-full overflow-scroll antialiased")}
        >
          {children}
        </body>
      </html>
    </>
  );
}
